name: Deploy ASP.NET Core MVC to Azure App Service

# This workflow is triggered on pushing to develop branch
on:
  push:
    branches:
      - develop
env:
  AZURE_WEBAPP_NAME: cs-core-mvc # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "3.1.x"           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}} 
      
      # Build .NET project
      - name: Restore Nuget packages
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/publish

      # Deploy to Azure Web apps
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{env.AZURE_WEBAPP_NAME}} # Replace with your app name
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}} # Define secret variable in repository settings as per action documentation
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/publish
